# Generated by Django 3.2.9 on 2021-11-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pickup_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pickup_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pickup_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pickup_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
