# Generated by Django 3.2.9 on 2021-11-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211113_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='delivery_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='delivery_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
