# Generated by Django 3.2.9 on 2021-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211113_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
