# Generated by Django 3.2.9 on 2021-11-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211114_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='jobs_listing/delivery_photo/'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pickedup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pickup_photo',
            field=models.ImageField(blank=True, null=True, upload_to='jobs_listing/pickup_photo/'),
        ),
    ]
