# Generated by Django 3.2.9 on 2021-11-16 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20211115_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='paystack_card_last4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='paystack_customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='paystack_payment_method_id',
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='courier/avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('Account_Bank_name', models.CharField(blank=True, max_length=255)),
                ('Account_name', models.CharField(blank=True, max_length=255)),
                ('Account_number', models.CharField(blank=True, max_length=255)),
                ('fcm_token', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.courier'),
        ),
    ]
